#!/usr/bin/env bash


current_date=$(date +"%d-%m-%Y")

mysqldump -u root -p"$1" --all-databases > backup.sql


tar -czvf "$current_date.tar.gz" backup.sql

rm backup.sql

echo "Backup created successfully: $current_date.tar.gz"
