#!/usr/bin/env bash
#script that displays "Best School" 10 times using until.


# Counter variable
count=0

# until loop to display "Best School" 10 times
until [ $count -eq 10 ]
do
    echo "Best School"
    ((count++))
done