#!/usr/bin/env bash
#script that displays "Best School" 9 times except one display "Hi" using while loop.

counter=1

while [ $counter -le 10 ]; do
    if [ $counter -eq 9 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi

    ((counter++))
done