#!/usr/bin/env bash

# Check if Apache is installed and modify its configuration if necessary
if [ -f /etc/apache2/ports.conf ]; then
    sed -i 's/Listen 8080/#Listen 8080/g' /etc/apache2/ports.conf
    pkill -1 apache2
fi

# Modify Nginx configuration
if [ -f /etc/nginx/nginx.conf ]; then
    sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
fi

# Modify Nginx default site configuration
if [ -f /etc/nginx/sites-available/default ]; then
    sed -i 's/80/8080/g' /etc/nginx/sites-available/default
fi

# Restart Nginx service
service nginx restart
